In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]
type(mylist)

list

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3])

In [6]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
mymatrix = np.array(mylist)
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
mymatrix.shape

(3, 3)

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones((3, 4)) * 500

array([[500., 500., 500., 500.],
       [500., 500., 500., 500.],
       [500., 500., 500., 500.]])

In [22]:
np.ones(4) * 10

array([10., 10., 10., 10.])

In [28]:
# Evenly spaced 
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [29]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(4)

array([0.08786859, 0.93857212, 0.76667082, 0.07736021])

In [33]:
np.random.rand(5,5)

array([[0.19389336, 0.65369076, 0.20363792, 0.39634191, 0.3956118 ],
       [0.02377388, 0.85944912, 0.57578018, 0.23409128, 0.8255854 ],
       [0.34069834, 0.3031118 , 0.80771791, 0.36240564, 0.73475244],
       [0.97579983, 0.63873342, 0.95619214, 0.83160443, 0.92767691],
       [0.96399385, 0.31727646, 0.85931676, 0.07448887, 0.07965162]])

In [35]:
np.random.randn(10)

array([ 0.43416297, -0.3707056 , -0.0294777 , -0.42246244, -0.44960334,
        1.34533199,  0.33241715,  3.31502374,  0.09065111,  2.61761703])

In [36]:
np.random.normal()

1.2868522582764335

In [37]:
np.random.randint(1, 100, 10)

array([73, 43, 78, 95, 80, 52, 17, 54, 46, 79])

In [39]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])